export const siteConfig = {
  name: "Chanikya Portfolio",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://chanikya-portfolio.pages.dev",
  description:
    "High-performance developer portfolio for Chanikya, a B.Tech CS student focused on modern full-stack engineering.",
  keywords: [
    "Chanikya",
    "Chanikya Jale",
    "Jale Chanikya",
    "chanikya jale",
    "jale chanikya",
    "j jale chanikya",
    "jale chanikya j",
    "j chanikya",
    "j. chanikya",
    "j chanikya jale",
    "chanikya",
    "j.chanikya",
    "chanikya developer",
    "chanikya portfolio",
    "j chanikya portfolio",
    "jale chanikya portfolio",
    "chanikya web developer",
    "chanikya full stack developer",
    "chanikya next.js developer",
    "chanikya software engineer",
    "B.Tech CS",
    "B.Tech Computer Science",
    "Computer Science Student Portfolio",
    "Developer Portfolio",
    "Full Stack Developer Portfolio",
    "Web Developer Portfolio",
    "Next.js",
    "Next.js Portfolio",
    "TypeScript",
    "Supabase",
    "Cloudflare Pages",
  ],
  author: {
    name: "Chanikya",
    alternateName: ["Jale Chanikya", "J Chanikya", "Chanikya Jale"],
    jobTitle: "B.Tech Computer Science Student",
  },
  socials: {
    github: "https://github.com/Chanikya-WebDev",
    linkedin: "https://www.linkedin.com/in/chanikya",
    x: "@chanikya",
  },
} as const;
